# Nama GitHub Action
name: Generate Pac-Man Animation

# Kapan Action ini dijalankan
on:
  schedule:
    # Atur untuk berjalan setiap 12 jam
    - cron: '0 */12 * * *'
  workflow_dispatch: # Juga bisa dijalankan secara manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout kode repositori Anda
      - uses: actions/checkout@v2

      # 2. Jalankan action untuk membuat animasi Pac-Man
      - name: Generate Pac-Man
        uses: ThaMainframe/github-profile-pacman@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Opsi: ganti 'main' jika branch utama Anda bukan 'main'
          # COMMIT_BRANCH: main 
          # Opsi: ganti nama file output jika Anda mau
          # COMMIT_FILE: https-profile-pacman.gif 

      # 3. Commit file GIF yang baru dibuat ke repositori Anda
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: Update Pac-Man animation" || exit 0
          git push
