name: Generate Pacman Contribution Graph

on:
  schedule:
    # Jalankan setiap 12 jam
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman-graph

    steps:
      # Langkah 1: Buat file SVG Pacman
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Action ini otomatis membuat file di dalam folder 'dist'

      # Langkah 2: Dorong file dari folder 'dist' ke branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # Nama branch tujuan
          target_branch: output
          # Nama folder sumber
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
